% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Aug-2018 11:20:53
%  MATLAB version: 9.0.0.341360 (R2016a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

imu_rawdata = saveVarsMat.imu_rawdata; % <7314x1 cell> too many elements

clear saveVarsMat;
